set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Iout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports done]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]


set_property PACKAGE_PIN T14 [get_ports clk]
set_property PACKAGE_PIN Y13 [get_ports {Iin[0]}]
set_property PACKAGE_PIN AB17 [get_ports {Iin[6]}]
set_property PACKAGE_PIN AB15 [get_ports {Iin[8]}]
set_property PACKAGE_PIN AA17 [get_ports {Iin[7]}]
set_property PACKAGE_PIN AA14 [get_ports {Iin[5]}]
set_property PACKAGE_PIN AB14 [get_ports {Iin[4]}]
set_property PACKAGE_PIN Y16 [get_ports {Iin[3]}]
set_property PACKAGE_PIN Y14 [get_ports {Iin[1]}]
set_property PACKAGE_PIN AA16 [get_ports {Iin[2]}]
set_property PACKAGE_PIN U10 [get_ports {Iout[6]}]
set_property PACKAGE_PIN Y8 [get_ports {Iout[1]}]
set_property PACKAGE_PIN AB8 [get_ports {Iout[7]}]
set_property PACKAGE_PIN AB9 [get_ports {Iout[8]}]
set_property PACKAGE_PIN U9 [get_ports {Iout[0]}]
set_property PACKAGE_PIN W8 [get_ports {Iout[3]}]
set_property PACKAGE_PIN W9 [get_ports {Iout[2]}]
set_property PACKAGE_PIN V10 [get_ports {Iout[5]}]
set_property PACKAGE_PIN V8 [get_ports {Iout[4]}]
set_property PACKAGE_PIN V15 [get_ports start]
set_property PACKAGE_PIN U12 [get_ports done]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]


